# Select image from https://hub.docker.com/_/php/
image: oprudkyi/laravel-bootstrap-adminlte-starter-kit:test-php-7.0

# Select what we should cache
cache:
  paths:
  - vendor
  - node_modules
  - .install-cache

before_script:
- ls -la 
- ls -la /cache
- "phantomjs --version"

# Install all project dependencies
- ./bootstrap.sh
- ./configure  
- make download-dependencies
- wget https://github.com/oprudkyi/Codeception/raw/wedriver-pageload-timeout/src/Codeception/Module/WebDriver.php -O vendor/codeception/codeception/src/Codeception/Module/WebDriver.php

services:
#- mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  #MYSQL_DATABASE: hello_world_test
  #MYSQL_ROOT_PASSWORD: mysql

# We test PHP7.0
test:
  script:
    - make -k check-functional
    - make -k check-acceptance
    - ls -la 
    - ls -la /cache
  allow_failure: true

# We test PHP7, but we allow it to fail
#test:php71:
#  image: php:7.1
#  script:
#    - make -k check-functional
#    - make -k check-acceptance
#  allow_failure: true

