# Select image from https://hub.docker.com/_/php/
image: php:7.0

# Select what we should cache
cache:
  paths:
  - vendor/
  - node_modules/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git curl 
        zip 
        npm ruby ruby-dev
        libmemcached-dev 
        libz-dev 
        libpq-dev 
        libjpeg-dev 
        libpng12-dev 
        libfreetype6-dev 
        libssl-dev 
        libmcrypt-dev -yqq

# Install php extensions
- docker-php-ext-install pdo_mcrypt
- docker-php-ext-install pdo_mysql
- docker-php-ext-configure gd 
        --enable-gd-native-ttf 
        --with-jpeg-dir=/usr/lib 
        --with-freetype-dir=/usr/include/freetype2 && 
        docker-php-ext-install gd

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- ./bootstrap.sh
- ./configure  
- make download-dependencies

services:
#- mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  #MYSQL_DATABASE: hello_world_test
  #MYSQL_ROOT_PASSWORD: mysql

# We test PHP7.0
test:
  script:
    - make -k check
    - make -k check-functional
    - make -k check-acceptance

# We test PHP7, but we allow it to fail
test:php71:
  image: php:7.1
  script:
    - make -k check
    - make -k check-functional
    - make -k check-acceptance
  allow_failure: true

