# Select image from https://hub.docker.com/_/php/
#
# there is used special image with some software preconfigured
# https://hub.docker.com/r/oprudkyi/laravel-bootstrap-adminlte-starter-kit
# https://github.com/oprudkyi/docker-laravel-bootstrap-adminlte-starter-kit
image: oprudkyi/laravel-bootstrap-adminlte-starter-kit:test-php-7.0

# Select what we should cache
cache:
  paths:
  - vendor
  - node_modules
  - .install-cache

before_script:
- ./bootstrap.sh
- ./configure  
- export COMPOSER_ALLOW_SUPERUSER=1

services:
#- mysql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
  #MYSQL_DATABASE: hello_world_test
  #MYSQL_ROOT_PASSWORD: mysql

# We test PHP7.0
test:php70:
  script:
    # Install all project dependencies
    - make install-dependencies
    # run tests
    - make -k check-functional
      #- timeout 600 node node_modules/phantomjs-prebuilt/bin/phantomjs --webdriver=4444 &
    - make -k check-acceptance

# We test PHP7.1, but we allow it to fail
test:php71:
  image: oprudkyi/laravel-bootstrap-adminlte-starter-kit:test-php-7.1
  script:
    # Install all project dependencies
    - make install-dependencies
    # run tests
    - make -k check-functional
    - make -k check-acceptance
  allow_failure: true

